"""Base abstract class and response model for model-agnostic LLM clients."""

from abc import ABC, abstractmethod
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, ConfigDict


class LLMResponse(BaseModel):
    """Encapsulates the standard response from any LLM provider."""
    model_config = ConfigDict(extra="ignore")

    content: str = Field(..., description="Raw text response generated by the model")
    raw_json: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Parsed JSON payload if structured output was requested and parsed"
    )
    model: str = Field(default="", description="Identifier of the model that generated output")
    provider: str = Field(default="", description="Provider name (e.g. openai, anthropic, fallback)")
    token_usage: Dict[str, int] = Field(
        default_factory=dict,
        description="Token accounting (prompt_tokens, completion_tokens, total_tokens)"
    )
    latency_ms: float = Field(default=0.0, description="Round-trip latency in milliseconds")


class BaseLLMClient(ABC):
    """Abstract interface for all LLM providers in AI Penfight.

    Ensures the pipeline is completely decoupled from any single vendor SDK.
    """

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        json_mode: bool = True,
        temperature: float = 0.3,
    ) -> LLMResponse:
        """Synchronously send a prompt to the LLM and return a standardized LLMResponse."""
        pass

    @abstractmethod
    async def generate_async(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        json_mode: bool = True,
        temperature: float = 0.3,
    ) -> LLMResponse:
        """Asynchronously send a prompt to the LLM and return a standardized LLMResponse."""
        pass

    @abstractmethod
    def is_available(self) -> bool:
        """Check if client credentials and endpoints are configured and reachable."""
        pass

    @abstractmethod
    def get_provider_name(self) -> str:
        """Return the lowercase name of the LLM provider."""
        pass
